PROJECT_ID = 'bigquery-devrel-samples'
DATASET_ID = 'test_dataset'
CURRENT_TABLE_ID = 'test_table'
NEW_TABLE_ID = 'test_table2'
GCS_INPUT_URI = 'gs://bigquery-devrel-samples-bucket/data.csv'
GCS_OUTPUT_URI = 'gs://bigquery-devrel-samples-bucket/output.csv'
