package com.google.cloud.bigquery.samples.test;


/**
 * TODO: Insert description here. (generated by elibixby)
 */
public class BigquerySampleTest {
  
  public static final String PROJECT_ID = "bigquery-devrel-samples";
  public static final String DATASET_ID = "test_dataset";
  public static final String CURRENT_TABLE_ID = "test_table";
  public static final String NEW_TABLE_ID = "test_table2";
  public static final String GCS_INPUT_URI = "gs://bigquery-devrel-samples-bucket/data.csv";
  public static final String GCS_OUTPUT_URI = "gs://bigquery-devrel-samples-bucket/output.csv";
  public static final String QUERY = "SELECT corpus FROM publicdata:samples.shakespeare GROUP BY corpus;";
  public static final String SCHEMA_PATH = "./test/data/schema.json";
  public static final String DATA_PATH = "./test/data/data.csv";
}
