package com.google.cloud.bigquery.samples;

import com.google.api.services.bigquery.Bigquery;
import com.google.api.services.bigquery.Bigquery.Jobs.GetQueryResults;
import com.google.api.services.bigquery.model.QueryRequest;
import com.google.api.services.bigquery.model.QueryResponse;
import com.google.api.services.bigquery.model.TableRow;

import java.io.IOException;
import java.io.PrintStream;
import java.util.List;
import java.util.Scanner;
/**
 * TODO: Insert description here. (generated by elibixby)
 */
public class SyncQuerySample extends BigqueryUtils{


  //[START main]
 /**
  * @param args
  * @throws IOException
  */
 public static void main(String[] args) 
     throws IOException{

  
   Scanner scanner = new Scanner(System.in);
   System.out.println("Enter your project id: ");
   String projectId = scanner.nextLine();
   System.out.println("Enter your query string: ");
   String queryString = scanner.nextLine();
   System.out.println("Enter how long to wait for the query to complete (in milliseconds):\n " +
                      "(if longer than 10 seconds, use an asynchronous query)");
   long waitTime = scanner.nextLong();
   System.out.println("Enter how many times to retry your query in case of a 500 response from server: ");
   int retries = scanner.nextInt();
   scanner.close();
   run(projectId, queryString, waitTime, retries, System.out);

 }
 // [END main]
  

 // [START run]
 public static void run(String projectId, 
     String queryString, 
     long waitTime, 
     int retries,
     PrintStream out) throws IOException{
   Bigquery bigquery = BigqueryServiceFactory.getService();
   //Wait until query is done with 10 second timeout, at most 5 retries on error
   QueryResponse query = execute(bigquery.jobs().query(
       projectId,
       new QueryRequest().setTimeoutMs(waitTime).setQuery(queryString)), 
       retries);
   
   //Make a request to get the results of the query 
   //(timeout is zero since job should be complete)
   
   GetQueryResults getRequest = bigquery.jobs().getQueryResults(
       query.getJobReference().getProjectId(),
       query.getJobReference().getJobId());
   
   
   for(List<TableRow> page: new QueryPages(getRequest, 5)){
     printRows(page, out);
   }
 }
 

}
